---
title: "Introduction to Mathing with R"
author: 
  name: "Created by [Jim Bang](http://www.github.com/bangecon)"
  email: BangJamesT@sau.edu
  affiliation: "[St. Ambrose University](http://www.sau.edu)"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: 
  learnr::tutorial: 
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(ggcheck)
gradethis_setup()
tutorial_options(exercise.reveal_solution = FALSE, exercise.eval = FALSE, exercise.checker = gradethis_exercise_checker)
knitr::opts_chunk$set(echo = FALSE)
```

## Solving a System of Equations: Supply and Demand

Given the following (inverse) supply and demand functions: 

$$P = \frac{10}{Q_d}$$

$$P = Q_s^2$$

1. Solve for the equilibrium price and quantity using `nleqslv::nleqslv`. 

```{r equilibrium, exercise = TRUE}

```

```{r equilibrium-solution, warning=FALSE, message = FALSE}
library(nleqslv)
equilibrium <- nleqslv(c(2,2), function(x) c(x[1]^2 - x[2], 10/x[1] - x[2]))
```

```{r equilibrium-check}
grade_this({
  if (!inherits(.result, c("list"))) {
    fail("Your class of your answer should be a list")}
  if (round(.result$x[1], 2) != 2.15) { 
    fail("The equilibrium quantity is about 2.15") }
  if (round(.result$x[2], 2) != 4.64) { 
    fail("The equilibrium price is about 4.64") }
  pass()
})
```

2. Graph the market equilibrium. Scale the x and y axes from 0 to 5 and 0 to 10, respectively. Add a point and label with the equilibrium values.

```{r equilibriumPlot, exercise = TRUE}

```

```{r equilibriumPlot-hint-1}
# The setup stores the result of the equilibrium solution as "equilibrium". 
# The element of the solution corresponding to the values for x (q, p) is "equilibrium$x".
```

```{r equilibriumPlot-hint-2}
# Use `geom_point(aes(x = equilibrium$x[1], y = equilibrium$x[2]))` for the point. 
# Use `geom_text(aes(x, y, label))` for the text label. 
```

```{r equilibriumPlot-hint-3}
# For the label argument use `paste0("(", `x value`, ", ", `y value`, ")") to 
# create a label with the solution values of q and p in parentheses.
```

```{r equilibriumPlot-setup, warning=FALSE, message = FALSE}
library(nleqslv)
equilibrium <- nleqslv(c(2,2), function(x) c(x[1]^2 - x[2], 10/x[1] - x[2]))
```

```{r equilibriumPlot-solution, warning=FALSE, message = FALSE}
library(ggplot2)
ggplot() + 
  geom_function(fun = function(x) 10/x) + 
  geom_function(fun = function(x) x^2) + 
  geom_point(aes(x = equilibrium$x[1], y = equilibrium$x[2])) +
  geom_text(
    aes(x = equilibrium$x[1], y = equilibrium$x[2]),
    label = 
      paste0("(", round(equilibrium$x[1], 2), ",", round(equilibrium$x[2], 2), ")"), 
    hjust = 0) +
  lims(x = c(0, 5), y = c(0, 10)) + 
  labs(x = "Quantity", y = "Price")
```

```{r equilibriumPlot-check}
grade_this({
  if (
    ith_geom_is(.result, "function", 1) & 
    ith_geom_is(.result, "function", 2) & 
    ith_geom_is(.result, "point", 3) & 
    ith_geom_is(.result, "text", 4)) {
    pass(random_praise())
  }
  fail(random_encouragement())
})
```
