---
title: "2.5 Technological Diffusion"
output: 
  learnr::tutorial: 
    progressive: true
runtime: shiny_prerendered
author: 
  name: "Created by [Jim Bang](http://www.github.com/bangecon)"
  email: BangJamesT@sau.edu
  affiliation: "[St. Ambrose University](http://www.sau.edu)"
date: "`r format(Sys.Date(), '%d %b %Y')`"
---

<style type="text/css">
#doc-metadata {
  margin-bottom: 10px;
  font-size: 0.8em;
}
</style>

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
gradethis_setup(exercise.reveal_solution = FALSE, exercise.eval = TRUE)
knitr::opts_chunk$set(echo = FALSE, fig.height = 6, fig.width = 6)
```

## Setup

```{r profitmaxGraph, exercise = TRUE}

```

```{r profitmaxGraph-solution}
```

```{r profitmaxGraph-check}
grade_code()
```

## Computational Approach

Find the solution to the profit-maximization problem numerically. 

Careful! Since our profit function has multiple "critical values" (points where change = 0), getting the correct solution will be sensitive to the initial value (`pars` option)

```{r profitmaxNumerical, exercise = TRUE}

```

```{r profitmaxNumerical-solution}

```

```{r profitmaxNumerical-check}
grade_this(
  if(round(.result$pars) != 10) {
    fail("The solution should be negligibly close to 10.")} 
  pass()
)
```

