---
title: "2.1 Production and Production Functions"
author: Jim Bang
output: 
  learnr::tutorial: 
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(Ryacas)
library(Deriv)
gradethis_setup(exercise.reveal_solution = FALSE)
knitr::opts_chunk$set(echo = FALSE, fig.height = 6, fig.width = 6)
```

## Increasing Returns to Scale

Suppose we have a production technology with diminishing returns to each individual input, but increasing returns to scale.  

$$ y = AL^{\alpha}K^{\beta},\text{ where}$$
$$ \alpha, \beta < 1 \text{, and}$$
$$\alpha + \beta > 1.$$
Suppose that $A = 100$ and $\alpha = \beta = 2/3$. 

1. Plot the short-run production function setting $K = 50$.

```{r shortrun, exercise = TRUE}

```

```{r shortrun-solution}
curve(100*x^(2/3)*50^(2/3),
  type = 'l',
  xlim = c(0, 50),
  xlab = "Labor",
  ylab = "Capital")
```

```{r shortrun-check}
grade_this({if (!inherits(.result, c("list"))) {
    fail("Your class of your answer should be a list")}
  if (round(.result$y[2], 3) != 854.988) { 
    fail("The second y value should equal 854.988.") }
  pass()
})
```

2. Calculate the output for the following combinations of inputs: 
  a. $(L, K) = (25, 25)$
  b. $(L, K) = (50, 50)$
  c. $(L, K) = (75, 75)$

```{r scale, exercise = TRUE}

```

```{r scale-solution}
y = function(L, K) {
  100*L^(2/3)*K^(2/3)
}
y(25,25)
y(50,50)
y(75,75)
```

```{r scale-check}
grade_this({if (round(.result, 2) != 31628.72) { 
    fail("The output for L = K = 75 should equal 31,628.72.") }
  pass("Notice that when we double or triple the inputs, production more than doubles or triples!")
})
```

3. Plot the isoquants for $Q = 25000$, $Q = 50000$, and $Q = 75000$

```{risoquants, exercise = TRUE}

```

```{r isoquants-solution}
curve((25000 / (100*x^(2/3)))^(3/2),
  type = 'l',
  ylim = c(0, 200),
  xlim = c(0, 200),
  xlab = "Labor",
  ylab = "Capital"
)
curve((50000 / (100*x^(2/3)))^(3/2), add = TRUE)
curve((75000 / (100*x^(2/3)))^(3/2), add = TRUE)
```

```{r isoquants-check}
grade_this({if (!inherits(.result, c("list"))) {
    fail("Your class of your answer should be a list")}
  if (round(.result$y[2], 3) != 10269.798) { 
    fail("The second y value should equal 10,269.798.") }
  pass()
})
```

