---
title: "Introduction to Mathing in R Practice"
author: "Jim Bang"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = 'center', fig.height = 6, fig.width = 6)
```

## Solving a System of Equations: Supply and Demand

Given the following (inverse) supply and demand functions: 

$$P = \frac{10}{Q_d}$$

$$P = Q_s^2$$

### Numerical Solution

```{r echo=TRUE}
library(nleqslv)
market <- function(x) {
  supply <- x[1] ^ 2 - x[2]
  demand <- 10 / x[1] - x[2]
  return(c(supply, demand))
}
equilibrium <- nleqslv(c(2, 2), market)$x
```


$$(`r equilibrium`)$$

### Graph of the Solution

```{r graph}
curve(10/x,
      from = 0 ,
      to = 5,
      col = 'blue',
      ylim = c(0, 10), 
      xlab = 'Quantity', 
      ylab = 'Price')
curve(x^2, col = 'darkorange', add = TRUE)
segments(x0 = 0, y0 = equilibrium[2], x1 = equilibrium[1], y1 = equilibrium[2])
segments(x0 = equilibrium[1], y0 = 0, x1 = equilibrium[1], y1 = equilibrium[2])
```

### Analytical Solution

```{r analytical}
library(Ryacas)
demandInverse <- ysym('10/Q')
supplyInverse <- ysym('Q^2')
Qstar <- solve(demandInverse, supplyInverse, 'Q')[[1]] |> 
  y_rmvars() 
Pstar <- with_value(demandInverse, 'Q', Qstar)
```

$$\Bigg(`r tex(Qstar)`, `r tex(Pstar)`\Bigg)$$
